@if(Session::has('success'))
    <div id="message_http" class="ui-pnotify  ui-pnotify-fade-normal ui-pnotify-mobile-able ui-pnotify-move ui-pnotify-in ui-pnotify-fade-in" aria-live="assertive" aria-role="alertdialog" style="display: none; width: 300px; right: 20px; top: 20px;"><div class="brighttheme ui-pnotify-container brighttheme-success ui-pnotify-shadow" role="alert" style="min-height: 16px;"><div class="ui-pnotify-closer" aria-role="button" tabindex="0" title="Close" style="cursor: pointer; visibility: hidden;"><span class="brighttheme-icon-closer"></span></div><div class="ui-pnotify-sticker" aria-role="button" aria-pressed="false" tabindex="0" title="Stick" style="cursor: pointer; visibility: hidden;"><span class="brighttheme-icon-sticker" aria-pressed="false"></span></div><div class="ui-pnotify-icon"><span class="icon-checkmark3"></span></div><h4 class="ui-pnotify-title">Success</h4><div class="ui-pnotify-text" aria-role="alert">{{Session::get('success')}}</div><div class="ui-pnotify-action-bar" style="margin-top: 5px; clear: both; text-align: right; display: none;"></div></div></div>
    <script>setTimeout(function() {$('#message_http').fadeOut('slow'); document.getElementById("message_http").remove();}, 5000);</script>
@endif

@if(Session::has('error'))
    <div id="message_http" class="ui-pnotify  ui-pnotify-fade-normal ui-pnotify-mobile-able ui-pnotify-in ui-pnotify-fade-in ui-pnotify-move" aria-live="assertive" aria-role="alertdialog" style="display: none; width: 300px; right: 20px; top: 20px; cursor: auto;"><div class="brighttheme ui-pnotify-container brighttheme-error ui-pnotify-shadow" role="alert" style="min-height: 16px;"><div class="ui-pnotify-closer" aria-role="button" tabindex="0" title="Close" style="cursor: pointer; visibility: hidden;"><span class="brighttheme-icon-closer"></span></div><div class="ui-pnotify-sticker" aria-role="button" aria-pressed="false" tabindex="0" title="Stick" style="cursor: pointer; visibility: hidden;"><span class="brighttheme-icon-sticker" aria-pressed="false"></span></div><div class="ui-pnotify-icon"><span class="icon-blocked"></span></div><h4 class="ui-pnotify-title">Error</h4><div class="ui-pnotify-text" aria-role="alert">{{Session::get('error')}}</div><div class="ui-pnotify-action-bar" style="margin-top: 5px; clear: both; text-align: right; display: none;"></div></div></div>
    <script>setTimeout(function() {$('#message_http').fadeOut('slow'); document.getElementById("message_http").remove();}, 5000);</script>
@endif

